spring.application.name=demo

#configuração de qual banco o hibernate vai se conectar
spring.datasource.url=jdbc:postgresql://localhost:5432/trabalho
spring.datasource.username=postgres
spring.datasource.password=12345

#configuração para que o hibernat recrie o banco de dados
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.generate-ddl=true

